name: Merge automatically created PR if it passed all checks

on:
  pull_request:
    types: [opened, synchronize]
  check_suite:
    types: [completed]

jobs:
  automerge:
    if: |
      github.event.pull_request.user.login == 'github-actions[bot]' &&
      github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Setup CLI
        run: |
          bash set_cli.sh
    
      - name: Wait for checks to succeed
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-checks
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            checkName: Build Documentation, Deploy pages
            ref: ${{ github.event.pull_request.head.sha || github.sha }}
        
      - name: Automerge
        if: steps.wait-for-checks.outputs.conclusion == 'success'
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "Enabling auto-merge for PR #$PR_NUMBER"
          
          gh pr merge $PR_NUMBER \
            --merge \
            --auto \
            --delete-branch \
            --body "Automatically merged after successful CI checks"
        env:
          GH_TOKEN: ${{ secrets.SOURCE_REPO_PAT }}
