name: Merge automatically created PR if it passed all checks

on:
  pull_request:
    types: [opened, synchronize]
  check_suite:
    types: [completed]

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Find pr_number if needed
        id: pr-info
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
            echo "sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          else
            PR_INFO=$(gh api "/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls" --jq '.[0] | {number: .number, sha: .head.sha}')
            echo "pr_number=$(echo $PR_INFO | jq -r '.number')" >> $GITHUB_OUTPUT
            echo "sha=$(echo $PR_INFO | jq -r '.sha')" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Checkout and setup
        uses: actions/checkout@v4
      
      - name: Setup CLI
        run: |
          bash set_cli.sh
      
      - name: Wait for checks
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-checks
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Build Documentation
          ref: ${{ steps.pr-info.outputs.sha || github.sha }}
      
      - name: Automerge
        if: steps.wait-for-checks.outputs.conclusion == 'success'
        run: |
          gh pr merge ${{ steps.pr-info.outputs.pr_number }} \
            --merge \
            --auto \
            --delete-branch
          
          sleep 10
          gh workflow run "Documentation Check" --ref main
          gh workflow run "Github Pages Deployment" --ref main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
